PROJECT_NAME = rxr

BAUD = 9600

MCU_NAME = atmega328pb

MCU_CODE = m328pb

MCU_FREQ = 16000000

CC = avr-gcc

LD = avr-objcopy

UPLOADER = avrdude

BIN_DIR = bin

BUILD_DIR = build

SOURCE_DIR = src

